### ISSUE TITLE
Missing data for object_class 23 - DASHBOARD 

### ISSUE THREAD

**Issue by CapNem0** [netxms/netxms-db-doc#1]
[object_containers](https://github.com/netxms/netxms-db-doc/blob/master/tables/object-containers.adoc)

Missing data for object_class 23  - should be DASHBOARD  
27 - should be BUSINESSERVICE_ROOT 

Other missing codes by now not found

**Comment by zev333** [comment]
BUSINESSERVICE_ROOT connection is not saved there
