### ISSUE TITLE
Иконки не включены в PDF

### ISSUE THREAD

**Issue by CapNem0** [netxms/netxms-db-doc#2]
Не критично, но квадратные скобки раздражают. При этом в HTML как "ключика" на месте

![Screenshot 2023-06-11 at 13 57 51](https://github.com/netxms/netxms-db-doc/assets/1137679/f4dd9d06-0ea9-4efa-8464-52d27959f788)
![Screenshot 2023-06-11 at 13 58 27](https://github.com/netxms/netxms-db-doc/assets/1137679/38d466ee-2a11-4c5b-a2aa-eaff44589890)

Mac OS Big Sur 
asciidoctor установлен через Homebrew 

Кроме того вылезла пара ошибок.
`asciidoctor: ERROR: the table cell on page 70 has been truncated; Asciidoctor PDF does not support table cell content that exceeds the height of a single page
asciidoctor: ERROR: the table cell on page 80 has been truncated; Asciidoctor PDF does not support table cell content that exceeds the height of a single page`

**Comment by alkk** [comment]
Занятно. Это не картинка, а символ Unicode. Подозреваю, что проблема с шрифтом.

**Comment by CapNem0** [comment]
ага, видел и даже проверил. 
Но в терминале файл *.adoc отображается верно. Хтмл тоже отображается верно. А вот ПДФ - нет.
![Screenshot 2023-06-11 at 17 23 38](https://github.com/netxms/netxms-db-doc/assets/1137679/2d7f4e67-075d-4f58-b85d-90e9b7698d43)

В терминале JetBrains Mono Nerd,

**Comment by alkk** [comment]
Да, реально что-то сломалось, [наша автоматическая сборка](https://netxms.org/documentation/datadictionary/netxms-data-dictionary.pdf) тоже кривая. Посмотрю, спасибо за информацию.
